# Site settings
title: 2TR Football
email: inof@2trfootball.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 2trofficial
github_username:  

# Build settings
markdown: kramdown
